---
- name: Install Docker
  gather_facts: No
  hosts: localhost
 
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
 
    - name: Install device-mapper-persistent-data
      yum:
        name: 
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
 
    
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
 
    
